// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdmXn-1ozKUTmFpZWeSwwGCv2s1zD8BMs',
    appId: '1:88481977773:web:34e4f3a902e7f9edfebd24',
    messagingSenderId: '88481977773',
    projectId: 'firstpro-37e05',
    authDomain: 'firstpro-37e05.firebaseapp.com',
    storageBucket: 'firstpro-37e05.appspot.com',
    measurementId: 'G-YJJ0E3YP26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaFpaObhfkKXNTumeo9n13S7E98ahbsiQ',
    appId: '1:88481977773:android:de27867b9ff99164febd24',
    messagingSenderId: '88481977773',
    projectId: 'firstpro-37e05',
    storageBucket: 'firstpro-37e05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-xJKGCmxdyLQ8gcNssC9cpQpCx-yu_gk',
    appId: '1:88481977773:ios:5721f3f87f281670febd24',
    messagingSenderId: '88481977773',
    projectId: 'firstpro-37e05',
    storageBucket: 'firstpro-37e05.appspot.com',
    androidClientId: '88481977773-nj6j275pd1tfsvbuofhcai64uj4qg1jb.apps.googleusercontent.com',
    iosClientId: '88481977773-d3o7uq63qobv8qbqn4t1hruqvn7m3vro.apps.googleusercontent.com',
    iosBundleId: 'com.example.memzoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-xJKGCmxdyLQ8gcNssC9cpQpCx-yu_gk',
    appId: '1:88481977773:ios:5721f3f87f281670febd24',
    messagingSenderId: '88481977773',
    projectId: 'firstpro-37e05',
    storageBucket: 'firstpro-37e05.appspot.com',
    androidClientId: '88481977773-nj6j275pd1tfsvbuofhcai64uj4qg1jb.apps.googleusercontent.com',
    iosClientId: '88481977773-d3o7uq63qobv8qbqn4t1hruqvn7m3vro.apps.googleusercontent.com',
    iosBundleId: 'com.example.memzoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_bVn0V3t3Br7I6Sx62rmCIV0iuhLaCu8',
    appId: '1:88481977773:web:97ef40694fe3b78bfebd24',
    messagingSenderId: '88481977773',
    projectId: 'firstpro-37e05',
    authDomain: 'firstpro-37e05.firebaseapp.com',
    storageBucket: 'firstpro-37e05.appspot.com',
    measurementId: 'G-SF19CQQ9MY',
  );
}
